version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    volumes:
      - public-data:/web/public
      - tmp-data:/web/tmp
    ports:
      - '80:80'
    depends_on:
      - rails

  rails:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    container_name: rails
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/web
      - tmp-data:/web/tmp
      - bundle:/bundle
    environment:
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - mysql

  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"

  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./package.json:/app/package.json
      - public-data:/app/public
      - ./frontend:/app/frontend
      - ./yarn.lock:/app/yarn.lock
      - node_modules:/app/node_modules

  # worker:
  #   build:
  #     context: .
  #     dockerfile: ./docker/rails/Dockerfile
  #   command: bundle exec sidekiq
  #   volumes_from:
  #     - rails
  #   links:
  #     - mysql
  #     - redis

  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379

volumes:
  public-data:
    driver: local
  tmp-data:
    driver: local
  mysql-data:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local